### ISSUE TITLE
Downloading the same files multiple times

### ISSUE THREAD

**Issue by rachel3834** [zhexingli/GetData#6]
Hi Zhexing, 
Sorry to bug you with this right after you head home, but it turns out that GetData is downloading the same files multiple times - it no longer seems to be skipping images like it did previously.  
Unfortunately, we are being charged every time we download a file, so this is causing a traffic spike.  
Do you have time to take a look?  If not, no worries, I will look tomorrow.  Thanks!

**Comment by zhexingli** [comment]
Hi Rachel,

Sorry about the problem of the code.... I would really want to have a look
and fix the bug but unfortunately I'm quite busy doing packaging and
housekeeping stuff. So I think the earliest time I could have a look at
that is Jun 17th or 18th, when I got him in China. Sry... If it's really
urgent, you could go ahead and take a look at the code. If so, let me know
the update you made!

Best,

Zhexing

2016-06-13 17:26 GMT-07:00 rachel3834 notifications@github.com:

**Comment by rachel3834** [comment]
OK, I have a fix for this issue.  Its happening as a result of the switch to the new pipeline data products, which have the catalog for each frame as part of the FITS file, rather than as a separate file. Since the cat files are no longer available, nothing was being recorded in the Catalog_.txt log and therefore the script had no memory of what it had previously downloaded.  

The fix I've implemented is to record the FITS images that have been downloaded in the Catalog_ log, since these also contain the catalogs anyway.  I've tested this and it works, but I cannot submit the fix to Github, as I don't have permission to contribute to this archive.  I can send the updated code and you can add it, or you can add me as a collaborator on this project if you prefer.

**Comment by rachel3834** [comment]
OK, I've committed my changes, so marking this issue as resolved.
